version: "3.8"
services:
  # backend:
  #   build:
  #     context: ./backend
  #   ports:
  #     - "5000:5000"
  #   depends_on:
  #     - redis
  #   environment:
  #     - POSTGRES_DB=${POSTGRES_DB:-ECRun}
  #     - POSTGRES_USER=${POSTGRES_USER:-ECRun}
  #     - POSTGRES_PASSWORD=${POSTGRES_PASSWORD:-!ChangeMe!}
  #     - REDIS_HOST=redis
  #   networks:
  #     - mynetwork
  #   volumes:
  #     - postgres_data:/var/lib/postgresql/data

  # redis:
  #   image: "redis:latest"
  #   networks:
  #     - mynetwork

  postgres-db:
    container_name: postgres-ecrun
    image: postgres:latest
    restart: always
    environment:
      - POSTGRES_DB=ECRun
      - POSTGRES_PASSWORD=!ChangeMe!
      - POSTGRES_USER=ECRun
      - PGDATA=/var/lib/postgresql/data/pgdata
    ports:
      - 5432:5432
    volumes:
      - postgres-db-ecrun:/var/lib/postgresql/data

volumes:
  postgres-db-ecrun:
    name: postgres-db-ecrun
